### ISSUE TITLE
Add About section or FAQ

### ISSUE THREAD

**Issue by shalva97** [klibs-io/issue-management#2]
**Is your feature request related to a problem? Please describe.**
for me it is unclear how libraries are added to your website or what is the future of it etc.

**Describe the solution you'd like**
Add an About section on the website. It could provide info about how website works and how I can add my library 

**Describe alternatives you've considered**
It could be a list of FAQ

**Comment by IgnatBeresnev** [comment]
There's now a [FAQ page](https://klibs.io/faq), thank you for the idea :) 

I'll close the issue as resolved, but do tell me if you think some other questions should be covered
